### ISSUE TITLE
xtrimomultimer/utils/__init__.py", line 2,  No module named 'xtrimomultimer.utils.rich_utils'

### ISSUE THREAD

**Issue by kehan777** [biomap-research/xTrimoMultimer#11]
python  /inference.py --help
>>>
Python 3.7.12
Traceback (most recent call last):
  File "/opt/xTrimoMultimer/inference.py", line 34, in <module>
    import xtrimomultimer.np.relax.relax as relax
  File "/opt/xTrimoMultimer/xtrimomultimer/np/relax/__init__.py", line 11, in <module>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "/opt/xTrimoMultimer/xtrimomultimer/np/relax/__init__.py", line 11, in <listcomp>
    _modules = [(m, importlib.import_module("." + m, __name__)) for m in __all__]
  File "/opt/conda/envs/xtrimomultimer/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/xTrimoMultimer/xtrimomultimer/np/relax/relax.py", line 19, in <module>
    from xtrimomultimer.np.relax import amber_minimize, utils
  File "/opt/xTrimoMultimer/xtrimomultimer/np/relax/amber_minimize.py", line 23, in <module>
    import xtrimomultimer.utils.loss as loss
  File "/opt/xTrimoMultimer/xtrimomultimer/utils/__init__.py", line 2, in <module>
    from xtrimomultimer.utils.rich_utils import enforce_tags, print_config_tree
ModuleNotFoundError: No module named 'xtrimomultimer.utils.rich_utils'

https://github.com/biomap-research/xTrimoMultimer/tree/main/xtrimomultimer/utils
cann't  find rich_utils.py and  rich_utils.py

**Comment by ssn1771** [comment]
i met the same problem，have you solved that？

**Comment by xianyu-123** [comment]
inference.py
# import xtrimomultimer.np.relax.relax as relax
utils/__init__.py
from xtrimomultimer.utils.logger import get_pylogger
# from xtrimomultimer.utils.rich_utils import enforce_tags, print_config_tree
# from xtrimomultimer.utils.utils import (
#     close_loggers,
#     extras,
#     get_metric_value,
#     instantiate_callbacks,
#     instantiate_loggers,
#     log_hyperparameters,
#     save_file,
#     task_wrapper,
# )

**Comment by addsg** [comment]
I met the same problem as you mention , have you ever solved it?

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢
