### ISSUE TITLE
only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by wwhhbuct** [biomap-research/xTrimoMultimer#9]
it failed to process features model. could anyone give a suggestion?

Traceback (most recent call last):
  File "inference.py", line 657, in <module>
    main(args)
  File "inference.py", line 566, in main
    is_multimer=global_is_multimer,
  File "/data/xTrimoMultimer/xtrimomultimer/data/feature_pipeline.py", line 108, in process_features
    mode=mode,
  File "/data/xTrimoMultimer/xtrimomultimer/data/feature_pipeline.py", line 77, in np_example_to_features
    num_res = int(np_example["seq_length"])
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by semal** [comment]
we use colabfold to generate feature pkl file to skip this step in xtrimomultimer, and it works. But find the result performance is lower than alphafold origin result.
